import { StyleSheet } from 'react-native';

export const finanzasStyles = StyleSheet.create({
  container: { flex: 1 },
  header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', padding: 20, paddingBottom: 25 },
  backBtn: { padding: 5 },
  titleContainer: { alignItems: 'center' },
  headerTitle: { color: '#fff', fontSize: 18, fontWeight: 'bold' },
  headerSubtitle: { color: '#e5e7eb', fontSize: 13, marginTop: 2 },
  tabs: { flexDirection: 'row', borderBottomWidth: 1, paddingHorizontal: 20 },
  tab: { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', paddingVertical: 12 },
  tabLabel: { marginLeft: 4, fontSize: 11 },
  tabHint: { fontSize: 12, paddingHorizontal: 20, paddingVertical: 8, textAlign: 'center' },
  tabPanel: { flex: 1, paddingHorizontal: 20 },
  tabScroll: { flex: 1 },
  sectionTitle: { fontSize: 17, fontWeight: 'bold', marginBottom: 10 },
  sectionSub: { fontSize: 13, lineHeight: 18, marginBottom: 14 },
  card: { flexDirection: 'row', alignItems: 'center', padding: 15, borderRadius: 5, marginBottom: 10, elevation: 1 },
  planIcon: { width: 44, height: 44, borderRadius: 22, justifyContent: 'center', alignItems: 'center', marginRight: 12 },
  planName: { fontSize: 15, fontWeight: '600' },
  planMonto: { fontSize: 16, fontWeight: 'bold' },
  badge: { paddingHorizontal: 8, paddingVertical: 2, borderRadius: 8, marginTop: 3 },
  monthRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', padding: 15, borderRadius: 5, marginTop: 15, marginBottom: 10 },
  statsRow: { flexDirection: 'row', gap: 10, marginBottom: 10 },
  statBox: { flex: 1, padding: 15, borderRadius: 5, alignItems: 'center', elevation: 1 },
  statMini: { flex: 1, padding: 10, borderRadius: 5, alignItems: 'center', elevation: 1 },
  generateBtn: { flexDirection: 'row', justifyContent: 'center', alignItems: 'center', padding: 14, borderRadius: 5, marginBottom: 15 },
  filterChip: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 14, paddingVertical: 8, borderRadius: 5, borderWidth: 1, marginRight: 8 },
  empty: { alignItems: 'center', marginTop: 40, paddingHorizontal: 16 },
  emptyTxt: { fontSize: 16, fontWeight: 'bold', marginTop: 10, textAlign: 'center' },
  emptySub: { fontSize: 13, marginTop: 8, textAlign: 'center', lineHeight: 18 },
  fab: { position: 'absolute', bottom: 20, right: 20, width: 60, height: 60, borderRadius: 30, justifyContent: 'center', alignItems: 'center', elevation: 5 },
  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.5)', justifyContent: 'flex-end' },
  modalContent: { borderTopLeftRadius: 5, borderTopRightRadius: 5, padding: 25, paddingBottom: 40 },
  modalHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 20 },
  modalTitle: { fontSize: 20, fontWeight: 'bold' },
  label: { fontSize: 13, marginBottom: 5, fontWeight: '600', marginLeft: 4 },
  input: { height: 48, borderWidth: 1, borderRadius: 5, paddingHorizontal: 15, marginBottom: 15 },
  textArea: { height: 80, paddingTop: 12 },
  saveBtn: { height: 50, borderRadius: 5, justifyContent: 'center', alignItems: 'center', flexDirection: 'row' },
  saveBtnTxt: { color: '#fff', fontSize: 16, fontWeight: 'bold' },
  actionBtn: { width: 60, justifyContent: 'center', alignItems: 'center', height: '100%' },
  payInfo: { padding: 15, borderRadius: 5, marginBottom: 15, alignItems: 'center' },
});
